### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by furieuxjk** [SergeyLukashevich/elektrum-lv-unofficial-api#1]
Hi!

Looks like Elektrum has changed something in their configuration, because by running this command:

`java -jar elektrum-fetcher-1.0.jar csv --period day -o output.csv 2019 2020`

I get this:

`2020-06-13 12:14:17,815 INFO [main] l.s.e.i.Client [Client.kt:59] Page 'https://mans.elektrum.lv/en/for-home/authorization/' has been opened
2020-06-13 12:14:23,905 INFO [main] l.s.e.i.Client [Client.kt:80] Authorization is successful
Exception in thread "main" com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 404 Not Found for https://www.elektrum.lv/en/for-home/consumption-report/smart-meters-data/consumption.json?step=D&fromDate=2019-01-01&tillDate=2020-01-01&useDateRange=1
        at com.gargoylesoftware.htmlunit.WebClient.throwFailingHttpStatusCodeExceptionIfNecessary(WebClient.java:581)
        at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:406)
        at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:313)
        at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:461)
        at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:446)
        at lv.sergluka.elektrum.inner.Client.fetch$api_main(Client.kt:99)
        at lv.sergluka.elektrum.ElektrumFetcher.fetchContinuous(ElektrumFetcher.kt:62)
        at lv.sergluka.elektrum.ElektrumFetcher.fetchHourly(ElektrumFetcher.kt:48)
        at command.base.CmdCommonOptions.fetchData(CmdCommonOptions.kt:68)
        at command.base.CmdCommonOptions.fetch(CmdCommonOptions.kt:56)
        at command.base.CmdCommonOptions.fetch$default(CmdCommonOptions.kt:52)
        at command.CmdExportCsv.run(CmdExportCsv.kt:28)
        at MainKt$main$1.invoke(Main.kt:28)
        at MainKt$main$1.invoke(Main.kt)
        at settings.Settings.get(Settings.kt:34)
        at MainKt.main(Main.kt:27)
`

Could you please try to reproduce?

**Comment by sergluka** [comment]
I'm sorry, but this project is no longer maintained.
